# Version needs to be specified
version: '2'

# Now volumes are first-class citizens & are declared separately from services
volumes:
  build:
    driver: local
  cache:
    external: true

# Now services are first-class citizens
services:
  test:
    # Build is more declarative
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache:/cache
      - build:/build
    # Add db to /etc/hosts in the test service container
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  agent:
    image: alexandrosv/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]

  db:
    image: mysql:5.6
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password